### ISSUE TITLE
Feature req

### ISSUE THREAD

**Issue by c0ff3e** [peregin/gps-overlay-on-video#91] opened 2022-04-16 15:36 UTC
Hello.

Tested it today, found that it dont seem to be able to handle gorpo7 4k video.
But i would love to see a overlay as the map used to sync, but as a overlay, thats something we that drive on racetracks would love to have.

Please let me know if i can help or assist in any way.

Br
Coffe

**Comment by KivraChristoffer** [comment] 2022-04-19 08:07
closing, duplicate of #47

**Comment by peregin** [comment] 2024-08-26 05:46
closing as duplicate of #47

**Closed by peregin** 2024-08-26 05:46 UTC
Labels: enhancement
